version: '2'
services:
  hadoop-slave1:
    image: registry.cn-hangzhou.aliyuncs.com/hadoop_test/hadoop_base
    container_name: hadoop-slave1
    volumes:
      - "./volume/hadoop/work/slave1:/works"
      - "./volume/hadoop/logs/slave1:/root/hadoop/logs/"
      - "./volume/hadoop/tmp/slave1:/tmp"
    hostname: hadoop-slave1
    networks:
      - hadoop
    tty: true
  
  hadoop-slave2:
    image: registry.cn-hangzhou.aliyuncs.com/hadoop_test/hadoop_base
    container_name: hadoop-slave2
    volumes:
      - "./volume/hadoop/work/slave2:/works"
      - "./volume/hadoop/logs/slave2:/root/hadoop/logs/"
      - "./volume/hadoop/tmp/slave2:/tmp"
    hostname: hadoop-slave2
    networks:
      - hadoop
    tty: true
      
  hadoop-master:
    image: registry.cn-hangzhou.aliyuncs.com/hadoop_test/hadoop_base
    container_name: Master
    ports:
      - "50070:50070"
      - "8088:8088"
    volumes:
      - "./volume/hadoop/work/master:/works"
      - "./volume/hadoop/logs/master:/root/hadoop/logs/"
      - "./volume/hadoop/tmp/master:/tmp"
      - "./volume/code:/code"
    hostname: hadoop-master
    links:
      - Slave1
      - Slave2 
    networks:
      - hadoop
    tty: true

networks:
  hadoop: